// ---------------------------------------------------------------------------
// Intelligence Matters - proprietary SKSE plugin
//
// Phase 16 - Stage A: validation plugin (load log).
// Phase 16 - Stage B: lean entry point. plugin.cpp implements nothing itself -
//   it only orchestrates the load:
//     1. Bring up the log        -> Log.cpp
//     2. Initialize SKSE         -> required before requesting any interface
//     3. Register Papyrus natives -> Papyrus.cpp (dispatcher)
//
//   No IM functionality goes here - that's Stage C. Every new module plugs
//   into the dispatcher (Papyrus.cpp), NOT into this file.
//
// Phase 16 - Stage C.1: a fourth step appears -
//     4. Register a message listener -> installs engine hooks on kDataLoaded
//
//   This is the one exception to "everything plugs into the dispatcher". The
//   dispatcher is for PAPYRUS NATIVES. Engine hooks are not natives: they have
//   no Papyrus surface and a different lifecycle (the vtable must exist, but
//   the VM need not be up). So hook installation gets its own seam here.
//
//   The exception is specific to C.1, which has no native at all - its channel
//   is a pair of globals. C.2 (external plugin) and C.3
//   (external plugin) DO expose natives and will plug into the dispatcher as
//   Stage B predicted.
//
//   kDataLoaded is the install point, and C.1 needs it: a vtable swap alone
//   would work earlier, but the module also caches the IM_CT_* TESGlobal
//   pointers, and those only resolve once plugin data is loaded.
// ---------------------------------------------------------------------------

// RE/Skyrim.h and SKSE/SKSE.h come from PCH.h (force-included by CMake).
#include "CastTime.h"
#include "Log.h"
#include "Papyrus.h"
#include "Version.h"

namespace
{
	// SKSE message dispatch. Fans out to whichever modules need a lifecycle
	// hook; today that is only CastTime.
	void OnMessage(SKSE::MessagingInterface::Message* a_msg)
	{
		if (!a_msg) {
			return;
		}

		if (a_msg->type == SKSE::MessagingInterface::kDataLoaded) {
			IMPlugin::CastTime::Install();
		}
	}
}

// SKSEPluginLoad is the modern CommonLibSSE-NG entry point. The version
// boilerplate (SKSEPlugin_Version) is auto-generated by add_commonlibsse_plugin.
SKSEPluginLoad(const SKSE::LoadInterface* a_skse) {
    // Without a log there's no way to diagnose anything - abort the load
    // explicitly instead of continuing blind.
    if (!IMPlugin::Log::Init()) {
        SKSE::stl::report_and_fail("SKSE log directory not provided.");
    }

    SKSE::Init(a_skse);

    spdlog::info("{} v{} loaded successfully.",
        IMPlugin::Version::kProjectName, IMPlugin::Version::kString);

    // Native function registration. SKSE calls the dispatcher once the
    // Papyrus VM is ready - that happens later during load, not right now.
    if (!SKSE::GetPapyrusInterface()->Register(IMPlugin::Papyrus::Register)) {
        spdlog::error("Failed to register the Papyrus callback - natives unavailable.");
        return false;
    }

    spdlog::info("Papyrus callback registered.");

    // Engine hook installation is deferred to kDataLoaded (see header comment).
    if (!SKSE::GetMessagingInterface()->RegisterListener(OnMessage)) {
        spdlog::error("Failed to register the SKSE message listener - hooks unavailable.");
        return false;
    }

    spdlog::info("Message listener registered.");

    return true;
}
