// ---------------------------------------------------------------------------
// Intelligence Matters - proprietary SKSE plugin
//
// Phase 16 - Stage A: validation plugin (load log).
// Phase 16 - Stage B: lean entry point. plugin.cpp implements nothing itself -
//   it only orchestrates the load:
//     1. Bring up the log        -> Log.cpp
//     2. Initialize SKSE         -> required before requesting any interface
//     3. Register Papyrus natives -> Papyrus.cpp (dispatcher)
//
//   No IM functionality goes here - that's Stage C. Every new module plugs
//   into the dispatcher (Papyrus.cpp), NOT into this file.
// ---------------------------------------------------------------------------

// RE/Skyrim.h and SKSE/SKSE.h come from PCH.h (force-included by CMake).
#include "Log.h"
#include "Papyrus.h"
#include "Version.h"

// SKSEPluginLoad is the modern CommonLibSSE-NG entry point. The version
// boilerplate (SKSEPlugin_Version) is auto-generated by add_commonlibsse_plugin.
SKSEPluginLoad(const SKSE::LoadInterface* a_skse) {
    // Without a log there's no way to diagnose anything - abort the load
    // explicitly instead of continuing blind.
    if (!IMPlugin::Log::Init()) {
        SKSE::stl::report_and_fail("SKSE log directory not provided.");
    }

    SKSE::Init(a_skse);

    spdlog::info("{} v{} loaded successfully.",
        IMPlugin::Version::kProjectName, IMPlugin::Version::kString);

    // Native function registration. SKSE calls the dispatcher once the
    // Papyrus VM is ready - that happens later during load, not right now.
    if (!SKSE::GetPapyrusInterface()->Register(IMPlugin::Papyrus::Register)) {
        spdlog::error("Failed to register the Papyrus callback - natives unavailable.");
        return false;
    }

    spdlog::info("Papyrus callback registered - Phase 16 Stage B.");

    return true;
}
