// ---------------------------------------------------------------------------
// Lodestone - Shared SKSE framework
//
// Phase 16 - Stage A: validation plugin (load log).
// Phase 16 - Stage B: lean entry point. plugin.cpp implements nothing itself -
//   it only orchestrates the load:
//     1. Bring up the log        -> Log.cpp
//     2. Initialize SKSE         -> required before requesting any interface
//     3. Register Papyrus natives -> Papyrus.cpp (dispatcher)
//
//   No IM functionality goes here - that's Stage C. Every new module plugs
//   into the dispatcher (Papyrus.cpp), NOT into this file.
//
// Phase 16 - Stage C.1: a fourth step appears -
//     4. Register a message listener -> installs engine hooks on kDataLoaded
//
//   This is the one exception to "everything plugs into the dispatcher". The
//   dispatcher is for PAPYRUS NATIVES. Engine hooks are not natives: they have
//   no Papyrus surface and a different lifecycle (the vtable must exist, but
//   the VM need not be up). So hook installation gets its own seam here.
//
//   Phase L0 update: CastTime now uses BOTH seams. It is an engine hook (installed
//   here on kDataLoaded) AND a native provider (RegisterCastTimeChannel, plugged
//   into the dispatcher like any other module). The two are independent: the hook
//   is passthrough until a consumer calls the native to register its channel.
//   C.2 (book text) and C.3 (spell tomes) also expose natives and plug into the
//   dispatcher as Stage B predicted.
//
//   kDataLoaded is the install point for the hook: a vtable swap alone would work
//   earlier, but the vtable must exist, and kDataLoaded is the established, safe
//   seam. The module no longer caches any globals here - they arrive at runtime
//   through the native.
// ---------------------------------------------------------------------------

// RE/Skyrim.h and SKSE/SKSE.h come from PCH.h (force-included by CMake).
#include "Core/BookFramework.h"
#include "Core/CastTime.h"
#include "Core/Log.h"
#include "Core/Papyrus.h"
#include "Core/SpellTomes.h"
#include "Version.h"

namespace
{
	// SKSE message dispatch. Fans out to whichever modules need a lifecycle
	// hook. CastTime swaps a vtable entry; BookFramework installs a branch hook on
	// the book-open function (which is why the trampoline is allocated below).
	void OnMessage(SKSE::MessagingInterface::Message* a_msg)
	{
		if (!a_msg) {
			return;
		}

		if (a_msg->type == SKSE::MessagingInterface::kDataLoaded) {
			Lodestone::Core::CastTime::Install();
			Lodestone::Core::BookFramework::Install();
			Lodestone::Core::SpellTomes::Install();
		}
	}
}

// SKSEPluginLoad is the modern CommonLibSSE-NG entry point. The version
// boilerplate (SKSEPlugin_Version) is auto-generated by add_commonlibsse_plugin.
SKSEPluginLoad(const SKSE::LoadInterface* a_skse) {
    // Without a log there's no way to diagnose anything - abort the load
    // explicitly instead of continuing blind.
    if (!Lodestone::Core::Log::Init()) {
        SKSE::stl::report_and_fail("SKSE log directory not provided.");
    }

    SKSE::Init(a_skse);

    spdlog::info("{} v{} loaded successfully.",
        Lodestone::Version::kProjectName, Lodestone::Version::kString);

    // Reserve trampoline space for branch hooks installed later (BookFramework
    // detours the book-open function on kDataLoaded). A vtable swap like CastTime's
    // needs none of this; a branch hook does, and it must be reserved before the
    // hook is written. 64 bytes covers the current single branch hook.
    SKSE::AllocTrampoline(64);

    // Native function registration. SKSE calls the dispatcher once the
    // Papyrus VM is ready - that happens later during load, not right now.
    if (!SKSE::GetPapyrusInterface()->Register(Lodestone::Core::Papyrus::Register)) {
        spdlog::error("Failed to register the Papyrus callback - natives unavailable.");
        return false;
    }

    spdlog::info("Papyrus callback registered.");

    // Engine hook installation is deferred to kDataLoaded (see header comment).
    if (!SKSE::GetMessagingInterface()->RegisterListener(OnMessage)) {
        spdlog::error("Failed to register the SKSE message listener - hooks unavailable.");
        return false;
    }

    spdlog::info("Message listener registered.");

    return true;
}
